---
tags: [spring-boot, gorm, groovy]
projects: [spring-boot, grails]
---
:spring_version: current
:spring_boot_version: 1.0.0.RC4
:Component: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Component.html
:Controller: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Controller.html
:DispatcherServlet: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/servlet/DispatcherServlet.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:ResponseBody: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/ResponseBody.html
:EnableAutoConfiguration: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/autoconfigure/EnableAutoConfiguration.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-accessing-data-gorm-mongodb

This guide walks you through the process of creating a Spring Boot application that uses Grails Object Relational Mapper (http://grails.org/doc/latest/guide/GORM.html[GORM]) and http://www.mongodb.org[MongoDB] for persistence. The application uses to http://grails.github.io/grails-data-mapping/mongo/manual/index.html[GORM for MongoDB plugin].

== What you'll build

You'll build a Spring application that persists geospatial data to MongoDB using GORM. 

NOTE: This guide only uses uses the Grails GORM library. You aren't required to use the full Grails web stack.


== What you'll need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


[[scratch]]
== Set up the project

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro.adoc[]

=== Create the directory structure

In a project directory of your choosing, create the following subdirectory structure; for example, with `mkdir -p src/main/groovy/cities` on *nix systems:

    └── src
        └── main
            └── groovy
                └── cities

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_both_builds.adoc[]

`build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::initial/build.gradle[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]


[[initial]]
== Create a GORM entity

In this example, we model a simple `City` entity using GORM:

`src/main/groovy/cities/City.groovy`
[source,groovy]
----
include::complete/src/main/groovy/cities/City.groovy[]
----

The http://grails.org/doc/latest/guide/GORM.html#gormConstraints[constraint block] defines any validation rules. In this case, we ensure that the `name` cannot be blank and the `location` cannot be `null`.

The http://grails.github.io/grails-data-mapping/mongo/manual/guide/3.%20Mapping%20Domain%20Classes%20to%20Mongo%20Collections.html#3.2%20Indexing%20Queries[mapping block] specifies that the `location` property should be indexed using a http://docs.mongodb.org/manual/core/2dsphere/[geospatial 2dsphere] index.

The `location` property is a `grails.mongodb.geo.Point` that gets persisted to MongoDB as a http://geojson.org/geojson-spec.html#id2[GeoJSON Point].

== Create a resource controller

Create a controller for your Groovy-based Spring application:

`src/main/groovy/cities/CityController.groovy`
[source,groovy]
----
include::complete/src/main/groovy/cities/CityController.groovy[]
----

The above example defines two REST endpoints:

- The `index` endpoint list all the known cities
- The `near` endpoint finds the city nearest to the specified city

The `populateCities` method is run at startup due to the presence of the `@PostConstruct` annotation. The method provides some initial data for the application to operate on. Notice how each city is provided a `Point` instance with the location specified in longitude / latitude order:

[source,groovy]
----
@PostConstruct
void populateCities() {
    City.withTransaction{
        City.collection.remove(new BasicDBObject())
        City.saveAll(
            [ new City(name:"London", 
                       location: Point.valueOf( [-0.125487, 51.508515] ) ),
              ...
              new City(name:"San Francisco", 
                       location: Point.valueOf( [-122.419416, 37.774929] ) ) ]
        )
    }
}
----

The `near` method takes the city name as parameter and then proceeds to find the nearest cities. Note that the first entry in the reult will be the city queried itself, so an index of 1 is used to find the closest city:

[source,groovy]
----
@RequestMapping(value="/near/{cityName}", method = GET)
ResponseEntity near(@PathVariable String cityName) {
    def city = City.findByName(cityName)
    if(city) {
        List<City> closest = City.findAllByLocationNear(city.location)
        return new ResponseEntity([name: closest[1].name], HttpStatus.OK)
    }
    ...
}
----

Further down in the guide, you'll see how to run the application.

== Make the application executable

Although it is possible to package this service as a traditional link:/understanding/WAR[WAR] file for deployment to an external application server, the simpler approach demonstrated below creates a standalone application. You package everything in a single, executable JAR file, driven by a good old Java `main()` method. Along the way, you use Spring's support for embedding the link:/understanding/Tomcat[Tomcat] servlet container as the HTTP runtime, instead of deploying to an external instance.


`src/main/groovy/cities/Application.groovy`
[source,groovy]
----
include::complete/src/main/groovy/cities/Application.groovy[]
----

The `main()` method defers to the {SpringApplication}[`SpringApplication`] helper class, providing `Application.class` as an argument to its `run()` method. This tells Spring to read the annotation metadata from `Application` and to manage it as a component in the link:/understanding/application-context[Spring application context].

The `@ComponentScan` annotation tells Spring to search recursively through the `hello` package and its children for classes marked directly or indirectly with Spring's {Component}[`@Component`] annotation. This directive ensures that Spring finds and registers the `GreetingController`, because it is marked with `@Controller`, which in turn is a kind of `@Component` annotation.

The {EnableAutoConfiguration}[`@EnableAutoConfiguration`] annotation switches on reasonable default behaviors based on the content of your classpath. For example, because the application depends on the embeddable version of Tomcat (tomcat-embed-core.jar), a Tomcat server is set up and configured with reasonable defaults on your behalf. And because the application also depends on Spring MVC (spring-webmvc.jar), a Spring MVC {DispatcherServlet}[`DispatcherServlet`] is configured and registered for you — no `web.xml` necessary! Auto-configuration is a powerful, flexible mechanism. See the {EnableAutoConfiguration}[API documentation] for further details.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]

[[testing]]
== Test the application

With the application started, you can create a new person by submitting a `POST` request. For example using the *nix `curl` tool:

[source,plain]
----
$ curl -i http://localhost:8080/
----

This results in the following response with the list of cities in JSON format:

[source]
----
$ curl -i http://localhost:8080/
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 21 Mar 2014 07:52:34 GMT

[{"name":"London"},{"name":"Paris"},{"name":"New York"},{"name":"San Francisco"}]
----

You can then submit a `GET` request to the `near` endpoint to find out which city is nearest to a specified city:

[source,plain]
----
$ curl -i http://localhost:8080/near/Paris
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 21 Mar 2014 07:53:47 GMT

{"name":"London"}
----

NOTE: This RESTful front end was coded for demonstration purposes. You can plug in GORM wherever you need it for your application.

== Groovy Script Support

The previous example required you to setup a Gradle or Maven build, but you can also use GORM in a simple Groovy script. 

As an example, create a new file called *app.groovy* and put the following code in it:

`app.groovy`
[source,groovy]
----
include::script/app.groovy[]
----

NOTE: It doesn't matter where the file is.

Next, https://github.com/spring-projects/spring-boot#installing-the-cli[install Spring Boot's CLI].

Run it as follows:

----
$ spring run app.groovy
----

NOTE: This assumes you shut down the previous application, to avoid a port collision.

Then simply follow the previous steps to <<testing,test the application>>.

== Configuring the MongoDB Connection

To configure the MongoDB connection settings you can use the application's `application.yml` file:

`src/main/resources/application.yml`
[source,groovy]
----
include::complete/src/main/resources/application.yml[]
----

The available configuration options are the same as those provided by the http://grails.github.io/grails-data-mapping/mongodb/manual/guide/2.%20Getting%20Started.html#2.3%20Advanced%20Configuration[MongoDB plugin for Grails].

Alternatively, if you have custom configuration requirements then you can configure a Spring bean of type `com.mongodb.Mongo` in your application.


== Summary

Congratulations! You've just developed a Spring application using GORM for MongoDB data access as well as a RESTful front end!



